name: Build R36S (aarch64)

on:
  push:
    branches: [main]
  workflow_dispatch: # botón manual en la UI de GitHub, sin hacer push

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Multiarch setup
        run: |
          sudo dpkg --add-architecture arm64
          sudo sed -i 's/^deb /deb [arch=amd64] /g' /etc/apt/sources.list
          echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports jammy main restricted universe" | sudo tee -a /etc/apt/sources.list
          echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports jammy-updates main restricted universe" | sudo tee -a /etc/apt/sources.list
          sudo apt-get update -y

      - name: Instalar dependencias ARM64
        run: |
          sudo apt-get install -y \
            gcc-aarch64-linux-gnu g++-aarch64-linux-gnu cmake \
            libsdl2-dev:arm64 \
            libgles2-mesa-dev:arm64 \
            libsdl2-dev:arm64 \
            libsdl2-2.0-0:arm64 \
            libegl1-mesa-dev:arm64 \
            libdrm-dev:arm64 \
            libgbm-dev:arm64

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-linux-gnu

      - name: Debug SDL2
        run: |
          find /usr -name "SDL2Config.cmake" 2>/dev/null || echo "NO ENCONTRADO"
          find /usr -name "sdl2-config.cmake" 2>/dev/null || echo "NO ENCONTRADO"

      - name: .cargo/config.toml
        run: |
          mkdir -p .cargo
          cat >> .cargo/config.toml << 'EOF'
          [target.aarch64-unknown-linux-gnu]
          linker = "aarch64-linux-gnu-gcc"
          EOF

      - name: Instalar Zig y cargo-zigbuild
        run: |
          sudo snap install zig --classic --beta
          cargo install cargo-zigbuild

      - name: Build
        env:
          PKG_CONFIG_ALLOW_CROSS: "1"
          PKG_CONFIG_PATH: "/usr/lib/aarch64-linux-gnu/pkgconfig"
          CC_aarch64_unknown_linux_gnu: "aarch64-linux-gnu-gcc"
          CXX_aarch64_unknown_linux_gnu: "aarch64-linux-gnu-g++"
          CMAKE_PREFIX_PATH_aarch64_unknown_linux_gnu: "/usr/lib/aarch64-linux-gnu"
          SDL2_DIR: "/usr/lib/aarch64-linux-gnu/cmake/SDL2" # ← nuevo
        run: |
          cargo zigbuild \
            --target aarch64-unknown-linux-gnu.2.31 \
            --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: game-r36s
          path: target/aarch64-unknown-linux-gnu/release/retro-game
